# Pre-commit configuration for AILang
repos:
  # AILang Validator
  - repo: local
    hooks:
      - id: ailang-validate
        name: AILang Validator
        entry: python -m validators.cli --no-suggestions
        language: system
        types: [file]
        files: ".*\\.ail$"
        exclude: "^(.+/)?(build|dist|.venv|.git|.mypy_cache|.pytest_cache|__pycache__)/"
        verbose: true
  
  # Python formatters and linters
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-pyyaml]
        args: [--strict, --ignore-missing-imports]
  
  # Check for merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  
  # Validate JSON files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
  
  # Validate Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.json]
