[tool.poetry]
name = "ailang"
version = "0.1.0"
description = "AILang Compiler and Runtime"
authors = ["Your Name <youremail@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
lark = "^1.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
